
BEGIN TRAN

--SELECT SEQ, CD_USERDEF1,CD_USERDEF2,CD_USERDEF3,CD_USERDEF4,CD_USERDEF5,CD_USERDEF6,CD_USERDEF7,CD_USERDEF8,CD_USERDEF9,CD_USERDEF10
-- INTO PRODUCT_DTL_BACKUP_20230227
-- FROM PRODUCT_DTL

ROLLBACK--COMMIT


BEGIN TRAN
ALTER TABLE PRODUCT_DTL ADD CD_USERDEF8 NVARCHAR(400)
ALTER TABLE PRODUCT_DTL ADD CD_USERDEF5 NVARCHAR(400)
ROLLBACK--COMMIT


BEGIN TRAN
UPDATE A 
   SET A.PARTNER = PI.PARTNER
	   --A.CD_USERDEF1 = PI.CD_USERDEF1, 
       --A.CD_USERDEF2 = PI.CD_USERDEF2, 
	   --A.CD_USERDEF3 = PI.CD_USERDEF3, 
	   --A.CD_USERDEF4 = PI.CD_USERDEF4, 
	   --A.CD_USERDEF5 = PI.CD_USERDEF5, 
	   --A.CD_USERDEF6 = PI.CD_USERDEF6, 
	   --A.CD_USERDEF7 = PI.CD_USERDEF7, 
	   --A.CD_USERDEF8 = PI.CD_USERDEF8, 
	   --A.CD_USERDEF9 = PI.CD_USERDEF9, 
	   --A.CD_USERDEF10 = PI.CD_USERDEF10,
	   --A.CD_USERDEF13 = PI.CD_USERDEF13,
	   --A.CD_USERDEF19 = PI.CD_USERDEF19

SELECT TOP 100 PI.*
  FROM PRODUCT_DTL A 
 INNER JOIN PRODUCT PRO ON A.PROSEQ = PRO.SEQ AND A.PROSEQ = 82890
 INNER JOIN PRODUCT_JEWELRY_DTL C ON A.PROSEQ = C.proseq
 INNER JOIN  (SELECT PARTNER,CD_ITEM,CD_USERDEF1,CD_USERDEF2,CD_USERDEF3,CD_USERDEF4,CD_USERDEF5,CD_USERDEF6,CD_USERDEF7,CD_USERDEF8,CD_USERDEF9,CD_USERDEF10,CD_USERDEF13,CD_USERDEF19
               FROM  ERP_LINK.NEOE.NEOE.MA_PITEM WHERE CD_COMPANY = '1000')PI ON PI.CD_ITEM =PRO.ERP_CD_ITEM     -- 제품기준으로 변경 )



SELECT PARTNER,* FROM PRODUCT_DTL WHERE PROSEQ = 82890
SELECT * FROM PRODUCT WHERE SEQ = 82890

  SELECT SEQ, CD_USERDEF13,CD_USERDEF19,CD_USERDEF1,CD_USERDEF2,CD_USERDEF3,CD_USERDEF4,CD_USERDEF5,CD_USERDEF6,CD_USERDEF7,CD_USERDEF8,CD_USERDEF9,CD_USERDEF10
  FROM WOORIM_230215.dbo.PRODUCT_DTL 
   WHERE PROSEQ = 82890

SELECT CD_USERDEF1,CD_USERDEF2,CD_USERDEF3,CD_USERDEF4,CD_USERDEF5,CD_USERDEF6,CD_USERDEF7,CD_USERDEF8,CD_USERDEF9,CD_USERDEF10
               FROM  ERP_LINK.NEOE.NEOE.MA_PITEM WHERE CD_COMPANY = '1000' AND CD_ITEM = 'SAG-09D96T-P4Y0000'


SELECT SEQ, CD_USERDEF1,CD_USERDEF2,CD_USERDEF3,CD_USERDEF4,CD_USERDEF5,CD_USERDEF6,CD_USERDEF7,CD_USERDEF8,CD_USERDEF9,CD_USERDEF10
 INTO PRODUCT_DTL_BACKUP_20230227
 FROM PRODUCT_DTL

SELECT * FROM ERP_LINK.NEOE.NEOE.MA_CODEDTL WHERE CD_COMPANY = '1000' AND CD_FIELD = 'MA_B000031'

BEGIN TRAN

INSERT INTO ERP_CODE_DTL (CD_FIELD,CD_SYSDEF,CD_COMPANY,FG1_SYSCODE,CD_USRDEF,NM_USRDEF,NM_SYSDEF,USE_YN,CD_FLAG1,CD_FLAG2,CD_FLAG3,NM_SYSDEF_E
,ID_INSERT,DTS_INSERT,ID_UPDATE,DTS_UPDATE,NM_SYSDEF_CH,NM_SYSDEF_JP,REMARK,NM_SYSDEF_L4,NM_SYSDEF_L5,NO_ORDER,NM_USERDEF_L1
,NM_USERDEF_L2)
SELECT CD_FIELD,CD_SYSDEF,CD_COMPANY,FG1_SYSCODE,CD_USRDEF,NM_USRDEF,NM_SYSDEF,USE_YN,CD_FLAG1,CD_FLAG2,CD_FLAG3,NM_SYSDEF_E
,ID_INSERT,DTS_INSERT,ID_UPDATE,DTS_UPDATE,NM_SYSDEF_CH,NM_SYSDEF_JP,REMARK,NM_SYSDEF_L4,NM_SYSDEF_L5,NO_ORDER,NM_USERDEF_L1
,NM_USERDEF_L2
 FROM ERP_LINK.NEOE.NEOE.MA_CODEDTL WHERE CD_COMPANY = '1000' AND CD_FIELD = 'MA_B000083'



SELECT * FROM ERP_CODE_DTL WHERE CD_FIELD = 'MA_B000083'

  
ROLLBACK -- COMMIT