-- SELECT DISTINCT B.SEQ, B.STORE FROM OWNMALL_BRAND_STORE_MAPPING A INNER JOIN STORE B ON A.STORE_SEQ = B.SEQ 
/*
SELECT	A.SET_GUBUN
	,	A.MODEL_NM
	,	A.MODEL_NO	
	,	C.RI_QTY
	,	C.VI_QTY
	,	B.*
  FROM LEADER_PRODUCT_IF	A
  LEFT JOIN LEADER_V_OPTION	B ON A.MODEL_NO = B.MODEL_NO
  LEFT JOIN LEADER_V_INV	C ON A.MODEL_NM = C.MODEL_NM
 WHERE 1=1
   AND A.SET_GUBUN = 'P'
   AND A.STORE_SEQ = 2417
   -- 기성
   AND B.PRODUCT_SEQ IS NOT NULL 
   AND C.RI_QTY > 0
   --AND C.VI_QTY = 0
   AND ENGRAVE = 'Y'	-- 안각인
   --AND ENGRAVEOUT = 'Y' -- 겉각인
 ORDER BY C.VI_QTY,C.RI_QTY DESC

*/
SELECT	A.SET_GUBUN
	,	A.MODEL_NM
	,	A.MODEL_NO	
	,	C.RI_QTY
	,	C.VI_QTY
	,	B.*
  FROM LEADER_PRODUCT_IF	A
  LEFT JOIN LEADER_V_OPTION	B ON A.MODEL_NO = B.MODEL_NO
  LEFT JOIN LEADER_V_INV	C ON A.MODEL_NM = C.MODEL_NM
 WHERE 1=1
   AND A.SET_GUBUN = 'P'
   AND A.STORE_SEQ = 2417
   -- 기성
   AND B.PRODUCT_SEQ IS NOT NULL 
   AND C.RI_QTY > 0
   --AND C.VI_QTY = 0
   AND ENGRAVE = 'Y'	-- 안각인
   --AND ENGRAVEOUT = 'Y' -- 겉각인
 ORDER BY C.VI_QTY,C.RI_QTY DESC

