SELECT * FROM CodeBook WHERE NAME LIKE '%생산%'
SELECT * FROM CodeBook WHERE CODE LIKE '%Team%'



SELECT * FROM LEADER_V_PRODUCT_INFO WHERE METALTYPE IS NOT NULL AND MOVEMENT IS NOT NULL AND CATEGORY = 'WATCH'
SELECT * FROM LEADER_V_PRODUCT_INFO WHERE METALTYPE IS NOT NULL AND MOVEMENT IS NOT NULL AND CATEGORY <> 'WATCH'
SELECT * FROM LEADER_V_PRODUCT_INFO WHERE CATEGORY = 'WATCH' AND BRAND_NAME LIKE 'STONEHENGE%' AND STONESMALLGROUP IS NOT NULL
SELECT * FROM LEADER_V_PRODUCT_INFO WHERE MODEL_NM = 'TEST 기성 + 주문제작 + 주문제작(각인)'


SELECT 	MODEL_NO			
,	CATEGORY			AS '구성'
,	METALTYPE			AS '소재'
,	MOVEMENT			AS '무브먼트'
,	GALSS				AS 'GLASS'
,	DIAL				AS 'DIAL'
,	WEIGHT				AS '중량'
,	SIZE				AS 'SIZE'
,	REMARK				AS '주요사양'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'WARRANTY_YN'		) AS '보증서 제공여부'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'MFG_COUNTRY'		) AS '제조국'
,	(SELECT SUB_CD_1 FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'PRECAUTIONS'	)	  AS '착용 시 주의사항'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'QA_STANDARD'		) AS '품질보증기준'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'AS_POC'			) AS 'A/S책임자'
FROM LEADER_V_PRODUCT_INFO WHERE MODEL_NO = 'SAW-22A01W-WIWMX19'


SELECT 	MODEL_NO			
,	CATEGORY			AS '구성'
,	METALTYPE			AS '소재'
,	STONESMALLGROUP		AS '스톤소재'
,	STONE				AS '스톤'
,	WEIGHT				AS '중량'
,	SIZE				AS 'SIZE'
,	REMARK				AS '주요사양'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'WARRANTY_YN'		) AS '보증서 제공여부'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'MFG_COUNTRY'		) AS '제조국'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'PRECAUTIONS'	)	  AS '착용 시 주의사항'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'QA_STANDARD'		) AS '품질보증기준'
,	(SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'AS_POC'			) AS 'A/S책임자'
FROM LEADER_V_PRODUCT_INFO WHERE MODEL_NO = 'SAG-15C28T-R4RCG11'

SELECT    A.MODEL_NO
		, CATEGORY	AS '구성'
		, METALTYPE			AS '소재'
		, MOVEMENT			AS '무브먼트'
		, GALSS				AS 'GLASS'
		, DIAL				AS 'DIAL'
		, WEIGHT			AS '중량'
		, SIZE				AS 'SIZE'
		, REMARK			AS '주요사양'
		, (SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'WARRANTY_YN'		) AS '보증서 제공여부'
		, (SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'MFG_COUNTRY'		) AS '제조국'
		, (SELECT SUB_CD_1 FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'PRECAUTIONS'	) AS '착용 시 주의사항'
		, (SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'QA_STANDARD'		) AS '품질보증기준'
		, (SELECT DETL FROM LEADER_V_COMMON WHERE GRP_CD = 'OWN_PRD_INFO' AND COM_CD = 'AS_POC'			) AS 'A/S책임자'

  FROM LEADER_V_PRODUCT_INFO A 
 WHERE MODEL_NO = 'RS#63-03MT'
	   






















