
-- TB_AS_SPEC

--DECLARE @TB_NAME VARCHAR(40)
--SET @TB_NAME = 'TB_AS_SPEC'


--EXEC MISSEC_LINK.MIS_SEC.DBO.sp_executesql N'SELECT * FROM INFORMATION_SCHEMA.COLUMNS'

EXEC MISSEC_LINK.MIS_SEC.DBO.sp_executesql 
	N'SELECT TABLE_NAME
	, COLUMN_NAME
	, DATA_TYPE
	, ISNULL(CAST(A.Character_Maximum_Length as VARCHAR), CAST(A.Numeric_Precision as VARCHAR) + '','' + CAST(A.Numeric_Scale as VARCHAR)) Column_Length,A.Column_Default
	, CASE WHEN A.Is_Nullable = ''YES'' THEN ''Y'' ELSE ''N'' END Is_Nullable
	, * 
FROM INFORMATION_SCHEMA.COLUMNS A WHERE TABLE_NAME = ''TB_AS_SPEC'' '


SELECT TOP 10 * 
 FROM MISSEC_LINK.MIS_SEC.DBO.TB_AS_SPEC A WITH(NOLOCK) 
 
ORDER BY REG_DATE DESC

--SELECT TABLE_NAME, COLUMN_NAME, IS_NULLABLE, DATA_TYPE,* FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_BRAND'




